Make it possible to disable SSE
owncloud/ocis-charts pull request #492
Opened 2024-02-23 12:22 UTC by 2403905

## Description
Make it possible to disable SSE
See [https://github.com/owncloud/ocis-charts/issues/491](#issue-491)

## Motivation and Context

## How Has This Been Tested?
locally on minikube

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

<!-- or create documentation PR in https://github.com/owncloud/docs-ocis/tree/master/modules/ROOT/pages/deployment/container>
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation generated (`make docs`) and committed
- [ ] Documentation ticket raised: <link>
- [ ] Documentation PR created: <link>

2024-02-26 09:32 UTC, d7oc reviewed
LGTM aside the small layout problem

2024-02-26 09:32 UTC, d7oc commented on charts/ocis/values.yaml
> +  # -- Disables server-sent events (sse). When disabled, clients will no longer receive sse notifications.
A line break as separator would be good here.

2024-02-26 14:58 UTC, 2403905 commented
@d7oc I added conditional running of the SSE service. Please have a look.

2024-02-27 06:18 UTC, wkloucek requested changes

2024-02-27 06:18 UTC, wkloucek commented on charts/ocis/docs/values.adoc.yaml
> +  disableSse: false
I'd prefere this to be in a sse subsection like:

```
features:
  sse:
    disabled: false
```

This makes it future proof regarding more sse settings

2024-03-04 14:26 UTC, d7oc approved these changes
LGTM

2024-03-04 15:16 UTC, merged