Added custom ca chain to deployments
owncloud/ocis-charts pull request #599
Opened 2024-06-11 15:55 UTC by b1schumacher

## Description
Added the custom CA Chain variables to the values.yaml and added the ca to to most important deployments.

## Related Issue

- Fixes [ #403](https://github.com/owncloud/ocis-charts/issues/403)

## Motivation and Context
Custom CA Chains are needed for multiple services, which require that ocis is trusting these ca's

## How Has This Been Tested?

- Tested the deployment with custom CA Chains

## Screenshots (if appropriate):

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

<!-- or create documentation PR in https://github.com/owncloud/docs-ocis/tree/master/modules/ROOT/pages/deployment/container>
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation generated (`make docs`) and committed
- [ ] Documentation ticket raised: <link>
- [ ] Documentation PR created: <link>

2024-06-12 09:55 UTC, d7oc commented on charts/ocis/templates/antivirus/deployment.yaml
> +            {{- end }}
Would be good to have this fragment templated so we don't have these lines in all `deployments.yml` file but only one with a call here.

suggestion

```
{{/*
oCIS ca mount

@param .path          The path to mount
*/}}
{{- define "ocis.caPath" -}}
            {{- if .Values.customCAChain.enabled }}
            - name: custom-ca-chain
              mountPath: {{ .path }}
            {{- end }}
{{- end -}}
```

Usage afterwards with `{{- include "ocis.caPath" /etc/ssl/certs }}`

2024-06-12 17:13 UTC, b1schumacher commented
I changed all the entries to a template and fixed also the issue that the customCAChain was overwriting the other CA files. 

Now there are two different directories, one with the default files and one with the custom CA chain. Both are added to the SSL_CERT_DIR variable.

2024-06-13 05:01 UTC, wkloucek commented
@b1schumacher I applied some formatting and added enabled this feature in the linting process.

So far I didn't get the pattern for which services the custom CA has been configured / skipped. Could you maybe elaborate why it's not on all services?

Also what's missing are the CronJobs, some of them only talk to NATS but even for this, we could make use of this feature.

2024-06-17 10:56 UTC, b1schumacher commented
@wkloucek I added the missing services and the jobs.

2024-07-12 13:04 UTC, wkloucek commented
I changed this to point to `stable-5` instead of `main` which is now tracking ocis rolling releases

2024-07-15 13:21 UTC, wkloucek commented on charts/ocis/values.yaml
> +  existingSecret: ""
Is there a particular reason for the CA chain to be put in a secret? From what I know, a CA chain is public information.

2024-07-24 13:56 UTC, wkloucek commented on charts/ocis/values.yaml
> +  existingSecret: ""
I changed it to a ConfigMap in https://github.com/owncloud/ocis-charts/pull/599/commits/e3443826ee3659970b262e7c767d2cac786a4c8d

2024-07-24 14:00 UTC, wkloucek approved these changes

2024-07-24 15:25 UTC, d7oc requested changes
LGTM aside the typo. Also verified locally via k3d.

2024-07-25 08:44 UTC, d7oc approved these changes
LGTM

2024-07-25 13:30 UTC, merged